name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.2.0
  firebase_core:
  firebase_auth:
  cloud_firestore:
  image_picker:
  modal_progress_hud:
  firebase_storage:
  rxdart:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  fonts:
    - family: Title
      fonts:
        - asset: fonts/Righteous-Regular.ttf
    - family: Sans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
